### PR TITLE
various updates

### PR DESCRIPTION
**Pull request by gferreira**
- separate UI code from lib code
- moving resources folder
- converting docs to markdown
- adding `.mechanic` file
- moving docs to README, copy with build script
- rebuilding extension package

### CODE REVIEW

**Comment by cjdunn** [comment]
Hmm, I'm still getting an error when trying to install your version of the extension
error

I tried in a few RF versions, from the latest beta: Version 3.4b (build 2003161944), to a few versions back: Version 3.4b (build 1912201425) and they all show this error when trying to install. If I run the build script after I download your repo then the extension will work, but not before then. I wonder if your version of the extension is working for anyone else without running the build script? 

When I run build script it says:
```
building extension... The python version 'python3.6' is not installed
 [Errno 2] No such file or directory: 'python3.6': 'python3.6'
done!

```

Could there be an issue with mojo ExtensionBundle? Or something strange about my setup? My machine is only a couple months old so I don't think I've installed anything unusual. Thanks again for you help troubleshooting this.

**Comment by cjdunn** [comment]
For now I'll merge in the PR and see if maybe it works for other people and just not for me?

**Comment by cjdunn** [comment]
@gferreira I merged your brach into Master and still getting “Hash does not match.​” when I try to install via Mechanic2. hmm

**Comment by gferreira** [comment]
well, yes, you’ve changed the contents of the extension, so the hash doesn’t match again…

- the icon URL should be updated in `MM2SpaceCenter.yml` in the `mechanic-2-server`, not in the extension
- why make it a trial and binary extension in the first place, if the source code is available?

**Comment by gferreira** [comment]
when working with compiled extensions:

- make changes in the source code (not in the extension package)
- run the build script again to rebuild the extension and recalculate the hash

**Comment by cjdunn** [comment]
Good point, I didn't intent to make it a binary and trial extension, I just wanted to try building via script and I thought a date was required. Even when I rebuild now I get the hash error. 

I'm tempted to just go back to building via the UI to see if that will work

**Comment by cjdunn** [comment]
Since I rebuild using the UI in RF it seems to work now via Mechanic. I would still love to be able to build a non-compiled extension via a script at some point. But for now this works. Thanks again for the help in troubleshooting this.

**Comment by gferreira** [comment]
hello @cjdunn, I’m glad you’ve managed to make it work. I’ve done some more tests and I’m getting unexpected “hash does not match” errors too (for example with the [Boilerplate extension]). now trying to find out where the problem is… the extensions can be installed manually, which is odd.

*to be continued...*

[Boilerplate extension]: https://github.com/roboDocs/rf-extension-boilerplate

**Comment by gferreira** [comment]
happy to inform that the issue has been fixed in the [latest beta](https://robofont.com/beta/downloads/)! thanks @typemytype

the cause of the problem were `Icon?` and `.DS_Store` files being used to create the hash, but not being pushed to the remote repo. (that’s why it worked locally)

@cjdunn please give the build script another try with the latest beta, it should work fine now. thanks for your patience and thanks for reporting!

**Pull request merged**
